version: '3'
services:
  backend:
    build: ./server
    volumes:
      - ./server:/usr/src/app
    ports:
      - 7000:7000
  
  frontend:
    build: ./client
    volumes:
      - ./client:/usr/src/app
    ports:
      - 19000:19000

